### ISSUE TITLE
AppVeyor is incorrectly registered to a noarch package

### ISSUE THREAD

**Issue by sodre** [conda-forge/python-slugify-feedstock#12]
Issue:
AppVeyor is trying to build python-slugify-feedstock which is a noarch python package.

Here is the error I get:
```
Build started
git clone -q https://github.com/conda-forge/python-slugify-feedstock.git C:\projects\python-slugify-feedstock-lqbe0
git fetch -q origin +refs/pull/10/merge:
git checkout -qf FETCH_HEAD
The build phase is set to "MSBuild" mode (default), but no Visual Studio project or solution files were found in the root directory. If you are not building Visual Studio project switch build mode to "Script" and provide your custom build command.
```
<br/>
Environment (<code>conda list</code>): the ci-build environment

**Comment by sodre** [comment]
@conda-forge/core,

The python-slugify noarch package is being incorrectly built on AppVeyor and failing. Is there a bot command to redo the CI (un)registration process?

**Comment by scopatz** [comment]
hmm if it is noarch, it shouldn't be built on AppVeyor on windows

**Comment by scopatz** [comment]
you should rerender the feedstock

**Comment by sodre** [comment]
I tried that locally and [using the bot](https://github.com/conda-forge/python-slugify-feedstock/pull/13#issuecomment-451463904). It did not really help as you can see from the bot's [comment](https://github.com/conda-forge/python-slugify-feedstock/pull/13#issuecomment-451464242)
